#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("rosary.Resource", IsApplication=true)]

namespace rosary
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Controls.Resource.String.library_name = global::rosary.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int androidcolors = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050010
			public const int black = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int black_overlay = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int blue = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int c1 = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int customeblue = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int darkblue = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int darkgreen = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int darkorange = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int darkpurple = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int darkred = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int green = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int lowDarkfont = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int orange = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int purple = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int red = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int white = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int whiteback = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int whitebackground = 2131034127;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BackgroundBlue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int menu = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rate = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int rosary = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rosary1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rosary3 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int share = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int whitebg = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000e
			public const int Rate_me = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int about = 2131296269;
			
			// aapt resource value: 0x7f09000b
			public const int add = 2131296267;
			
			// aapt resource value: 0x7f090004
			public const int btnClear = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int btnClick = 2131296262;
			
			// aapt resource value: 0x7f090009
			public const int btnclear_all = 2131296265;
			
			// aapt resource value: 0x7f090005
			public const int button1 = 2131296261;
			
			// aapt resource value: 0x7f09000c
			public const int clear_all = 2131296268;
			
			// aapt resource value: 0x7f090008
			public const int etxt_all = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int etxt_result = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int linearLayout5 = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int linearLayout6 = 2131296256;
			
			// aapt resource value: 0x7f09000a
			public const int share = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int textView2 = 2131296263;
			
			// aapt resource value: 0x7f090001
			public const int txtresult = 2131296257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int about = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int add = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int clear_all = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int rate = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int reset = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int result = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int share = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int txtall = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyCustomTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
